# Test der Elementfunktionen Wärmeleitung 2D

In [4]:
import numpy as np
%load_ext autoreload
%autoreload 2

## Knoten eines Elements

In [5]:
x = np.array([[0.0, 1.2, 0.3], [0.1, 0.2, 2.5]])

## Referenzwerte

In [6]:
keRef = np.array(
    [[ 1.39122807, -1.19736842, -0.19385965],
    [-1.19736842,  1.33421053, -0.13684211],
    [-0.19385965, -0.13684211,  0.33070175]]
)
reRef = np.array([1.9475, 1.9475, 1.9475])

## Berechnung und Vergleich

### Elementmatrix

In [10]:
#from heat import *
x = np.array([[0.0, 1.2, 0.3], [0.1, 0.2, 2.5]])

def heatKe (lambder):
    def computeKe(x):
        Ke = np.zeros([3,3])
        u = x[:,1] - x[:,0]
        v = x[:,2] - x[:,1]
        w = x[:,0] - x[:,2]
        Ae = 1/2 * np.abs(np.cross(u,v))
        Be = 1/(2*Ae) * np.array([[v[1],w[1],u[1]],[-v[0],-w[0],-u[0]]])
        print('Be =',Be)
        #print('BeT =',Be.T)
        #print(np.dot(Be,Be.T))
        Ke = lambder * Ae * np.dot(Be.T,Be) 
        #print('Ke =',Ke)
        return Ke
    return computeKe

kef = heatKe(1.3)
ke = kef(x)

print('Ke =', ke)
if np.linalg.norm(ke - keRef) < 1e-8:
    print('--> Elementmatrix OK')
else:
    print('--> Elementmatrix nicht OK')

Be = [[ 0.80701754 -0.84210526  0.03508772]
 [ 0.31578947  0.10526316 -0.42105263]]
Ke = [[ 1.39122807 -1.19736842 -0.19385965]
 [-1.19736842  1.33421053 -0.13684211]
 [-0.19385965 -0.13684211  0.33070175]]
--> Elementmatrix OK


### Elementvektor

In [9]:

def heatRe(w):
    def computeRe(x):
        u = x[:,1] - x[:,0]
        v = x[:,2] - x[:,1]
        Ae = abs(1/2 * (u[0]*v[1] - u[1]*v[0]))
        Re = 1/3 * w * Ae * np.array([1, 1, 1])
        return Re
    return computeRe

ref = heatRe(4.1)
re = ref(x)

print('\nre =', re)
if np.linalg.norm(re - reRef) < 1e-8:
    print('--> Elementvektor OK')
else:
    print('--> Elementvektor nicht OK')




re = [1.9475 1.9475 1.9475]
--> Elementvektor OK
