# Übungsblatt 6

In [1]:
import numpy as np
import matplotlib.pyplot as plt 
import math 
from objdict import ObjDict
from fun

%load_ext autoreload
%autoreload

## Aufgabe 2.2

In [2]:
def heatKe(lambder):
    def computeKe(x):
        Ke = np.zeros([3,3])
        u = x[:,1] - x[:,0]
        v = x[:,2] - x[:,1]
        w = x[:,0] - x[:,2]
        Ae = 1/2 * np.abs(np.cross(u,v))
        Be = 1/(2*Ae) * np.array([[v[1],w[1],u[1]],[-v[0],-w[0],-u[0]]])
        print('Be =',Be)
        #print('BeT =',Be.T)
        #print(np.dot(Be,Be.T))
        Ke = lambder * Ae * np.dot(Be.T,Be) 
        print('Ke =',Ke)
        return Ke
    return computeKe

def heatRe(w):
    def computeRe(x):
        u = x[:,1] - x[:,0]
        v = x[:,2] - x[:,1]
        Ae = abs(1/2 * (u[0]*v[1] - u[1]*v[0]))
        Re = 1/3 * w * Ae * np.array([1, 1, 1])
        return Re
    return computeRe

x = np.array([[0.0, 1.2, 0.3], [0.1, 0.2, 2.5]])

keRef = np.array([
    [1.39122807, -1.19736842, -0.19385965],
    [-1.19736842, 1.33421053, -0.13684211],
    [-0.19385965, -0.13684211, 0.33070175]
])

reRef = np.array([1.9475, 1.9475, 1.9475])

kef = heatKe(1.2)
ke = kef(x)

print(ke)

if np.linalg.norm(ke - keRef) < 1e-8:
    print("--> Element matrix OK")
else:
    print("--> Element matrix not OK")

ref = heatRe(4.1)
re = ref(x)

print(re)
if np.linalg.norm(re - reRef) < 1e-8:
    print("--> Element vector OK")
else:
    print("--> Element vector not OK")

[[ 1.28421053 -1.10526316 -0.17894737]
 [-1.10526316  1.23157895 -0.12631579]
 [-0.17894737 -0.12631579  0.30526316]]
--> Element matrix not OK
[1.9475 1.9475 1.9475]
--> Element vector OK


## Aufgabe 2.4