# Test Dirichlet BCs

In [3]:
%load_ext autoreload
%autoreload 2

from fem import *

K = np.arange(1, 26).reshape(5, 5)
r = np.arange(1, 6)

print('Vorher')
print('K =\n', K)
print('r =\n', r)

applyDirichletBCs([1, 3], K, r)

print('Nachher')
print('K =\n', K)
print('r =\n', r)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
Vorher
K =
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
r =
 [1 2 3 4 5]
Nachher
K =
 [[ 1  2  3  4  5]
 [ 0  1  0  0  0]
 [11 12 13 14 15]
 [ 0  0  0  1  0]
 [21 22 23 24 25]]
r =
 [1 0 3 0 5]
